// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Models;

namespace Server.Migrations
{
    [DbContext(typeof(AgencijaContext))]
    partial class AgencijaConextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Server.Models.Agencija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adresa");

                    b.Property<string>("kontakTelefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kontakTelefon");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.Property<string>("vlasnik")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vlasnik");

                    b.HasKey("ID");

                    b.ToTable("Agencije");
                });

            modelBuilder.Entity("Server.Models.Aranzman", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("agencijaID")
                        .HasColumnType("int");

                    b.Property<int>("brojDana")
                        .HasColumnType("int")
                        .HasColumnName("brojDana");

                    b.Property<int>("brojMesta")
                        .HasColumnType("int")
                        .HasColumnName("brojMesta");

                    b.Property<int>("brojZauzetihMesta")
                        .HasColumnType("int")
                        .HasColumnName("brojZauzetihMesta");

                    b.Property<int>("cena")
                        .HasColumnType("int")
                        .HasColumnName("cena");

                    b.Property<DateTime>("datumPolaska")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumPolaska");

                    b.Property<DateTime>("datumPovratka")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumPovratka");

                    b.Property<string>("naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slika");

                    b.Property<string>("tip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tip");

                    b.HasKey("ID");

                    b.HasIndex("agencijaID");

                    b.ToTable("Aranzmani");
                });

            modelBuilder.Entity("Server.Models.Musterija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("aranzmanID")
                        .HasColumnType("int");

                    b.Property<int>("brojPasosa")
                        .HasColumnType("int")
                        .HasColumnName("brojPasosa");

                    b.Property<int>("brojSaputnika")
                        .HasColumnType("int")
                        .HasColumnName("brojSaputnika");

                    b.Property<DateTime>("datumRodjenja")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumRodjenja");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ime");

                    b.Property<string>("kontaktTelefon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kontaktTelefon");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prezime");

                    b.HasKey("ID");

                    b.HasIndex("aranzmanID");

                    b.ToTable("Musterije");
                });

            modelBuilder.Entity("Server.Models.Saputnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brojPasosa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brojPasosa");

                    b.Property<string>("ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ime");

                    b.Property<int?>("musterijaID")
                        .HasColumnType("int");

                    b.Property<string>("prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prezime");

                    b.HasKey("ID");

                    b.HasIndex("musterijaID");

                    b.ToTable("Saputnici");
                });

            modelBuilder.Entity("Server.Models.Aranzman", b =>
                {
                    b.HasOne("Server.Models.Agencija", "agencija")
                        .WithMany("aranzmani")
                        .HasForeignKey("agencijaID");

                    b.Navigation("agencija");
                });

            modelBuilder.Entity("Server.Models.Musterija", b =>
                {
                    b.HasOne("Server.Models.Aranzman", "aranzman")
                        .WithMany("musterije")
                        .HasForeignKey("aranzmanID");

                    b.Navigation("aranzman");
                });

            modelBuilder.Entity("Server.Models.Saputnik", b =>
                {
                    b.HasOne("Server.Models.Musterija", "musterija")
                        .WithMany("saputnici")
                        .HasForeignKey("musterijaID");

                    b.Navigation("musterija");
                });

            modelBuilder.Entity("Server.Models.Agencija", b =>
                {
                    b.Navigation("aranzmani");
                });

            modelBuilder.Entity("Server.Models.Aranzman", b =>
                {
                    b.Navigation("musterije");
                });

            modelBuilder.Entity("Server.Models.Musterija", b =>
                {
                    b.Navigation("saputnici");
                });
#pragma warning restore 612, 618
        }
    }
}
